language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
"scripts": {
    "start": "SET NODE_ENV=dev && node server.js",
    "test": "istanbul cover nyc mocha --exit",
    "coverage": "nyc report"}
after_success: npm run coverage
addons:
    code_climate:
        repo_token: b8409b53a4602ed1e72f219fb3411fc47ce046a27ef0f9ed51d0818982ad46d5
  before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info