language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
env:
  global:
    - CC_TEST_REPORTER_ID=b8409b53a4602ed1e72f219fb3411fc47ce046a27ef0f9ed51d0818982ad46d5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
"scripts": {
    "start": "SET NODE_ENV=dev && node server.js",
    "test": "nyc mocha --exit",
    "coverage": "nyc report"}
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
